#!/usr/bin/env bash
#   will create a file /var/run/myscript.pid containing the script's PID.
#   Displays "To infinity and beyond" indefinitely
#   Displays "I hate the kill command" when command SIGTERM
#   Displays "Y U no love me?!" when command SIGINT
#   Deletes the earlier pid file and terminates when
#   receiving command SIGQUIT or SIGTERM.

echo "$$" > /var/run/myscript.pid

# Function to handle signals
function handle_signal {
    signal=$1
    case $signal in
        SIGTERM | SIGQUIT)
            # Delete PID file and terminate
            rm /var/run/myscript.pid
            exit 0
            ;;
        SIGINT)
            echo "Y U no love me?!"
            ;;
        *)
            echo "I hate the kill command"
            ;;
    esac
}

# Set signal handlers
trap 'handle_signal SIGTERM' SIGTERM
trap 'handle_signal SIGQUIT' SIGQUIT
trap 'handle_signal SIGINT' SIGINT

# Loop forever and display message
while true; do
    echo "To infinity and beyond"
    sleep 2
done
