#!/usr/bin/env bash
# this code will print 1-100
count=1

while [ $count -le 100 ]
do
	if (( $count % 3 == 0)) && (( $count % 5 == 0))
	then
		echo "FizzBuzz"
	elif (( $count % 3 == 0))
	then
		echo "Fizz"
	elif (( $count % 5 == 0))
	then
		echo "Buzz"
	else
		echo "$count"
	fi
	count=$((count+1))
done
