#!/usr/bin/env bash
# this is the passwd story just run it and see

while IFS=':' read -r user passwd uid gid name home shell;
do
  echo "The user $user is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode $passwd, more info about the user here: $name"
done < "/etc/passwd"
